# Generated by Django 5.2.3 on 2025-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isletme_adi', models.CharField(max_length=100)),
                ('resim', models.ImageField(upload_to='galeri/')),
                ('aciklama', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GenelAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isletme_adi', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='logolar/')),
            ],
        ),
        migrations.CreateModel(
            name='Hizmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmet_adi', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('detayli_aciklama', models.TextField()),
                ('seans_suresi', models.IntegerField(help_text='Dakika cinsinden')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hizmet_fotografi', models.ImageField(upload_to='hizmet_fotograflari/')),
                ('acilis_saati', models.TimeField()),
                ('kapanis_saati', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IletisimBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('il', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=50)),
                ('mahalle', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('hizmetler', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tarih', models.DateField()),
                ('seans_baslangic', models.TimeField()),
                ('seans_bitis', models.TimeField()),
                ('hizmet_adi', models.CharField(max_length=100)),
                ('hizmet_suresi', models.IntegerField(help_text='Dakika cinsinden')),
                ('personel_adi', models.CharField(max_length=100)),
                ('isletme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.CharField(max_length=255)),
                ('cevap', models.TextField()),
            ],
        ),
    ]
