# Generated by Django 5.2.3 on 2025-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayar',
            name='guncellenme',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
