# Generated by Django 5.2.3 on 2025-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0002_genelayar_guncellenme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genelayar',
            name='guncellenme',
        ),
        migrations.AlterField(
            model_name='genelayar',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
