# Generated by Django 5.2.3 on 2025-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0004_genelayar_guncellenme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='aciklama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
