# Generated by Django 5.2.3 on 2025-06-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0005_alter_galeri_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmet',
            name='acilis_saati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='kapanis_saati',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
