# Generated by Django 5.2.3 on 2025-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0006_alter_hizmet_acilis_saati_alter_hizmet_kapanis_saati'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayar',
            name='acilis_saati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genelayar',
            name='kapanis_saati',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
