# Generated by Django 5.2.3 on 2025-06-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0007_genelayar_acilis_saati_genelayar_kapanis_saati'),
    ]

    operations = [
        migrations.AddField(
            model_name='sss',
            name='siralama',
            field=models.IntegerField(default=0),
        ),
    ]
