# Generated by Django 5.2.3 on 2025-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0008_sss_siralama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='hizmetler',
            field=models.TextField(),
        ),
    ]
