# Generated by Django 5.2.3 on 2025-07-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0009_alter_personel_hizmetler'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='sira',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
