# Generated by Django 5.2.3 on 2025-07-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0010_galeri_sira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'ordering': ['sira']},
        ),
    ]
