# Generated by Django 5.2.3 on 2025-07-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0012_hizmet_sira'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sss',
            options={'ordering': ['siralama']},
        ),
    ]
