# Generated by Django 5.2.3 on 2025-07-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0013_alter_sss_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personel',
            name='hizmetler',
        ),
        migrations.AddField(
            model_name='personel',
            name='hizmetler',
            field=models.ManyToManyField(related_name='personeller', to='randevu_app.hizmet'),
        ),
    ]
