# Generated by Django 5.2.3 on 2025-07-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0014_remove_personel_hizmetler_personel_hizmetler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personel',
            name='hizmetler',
        ),
        migrations.AddField(
            model_name='personel',
            name='hizmetler',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
