# Generated by Django 5.2.3 on 2025-07-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0017_merge_0015_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randevu',
            old_name='email_notif',
            new_name='email_bilgilendirme',
        ),
    ]
