# Generated by Django 5.2.3 on 2025-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0018_rename_email_notif_randevu_email_bilgilendirme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='seans_baslangic',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='seans_bitis',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
