# Generated by Django 5.2.3 on 2025-07-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0019_alter_randevu_seans_baslangic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='durum',
            field=models.CharField(default='bekleyen', max_length=20),
        ),
    ]
