# Generated by Django 5.2.3 on 2025-07-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0020_randevu_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='hizmet_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
