# Generated by Django 5.2.3 on 2025-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0021_randevu_hizmet_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='hizmet_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
