# Generated by Django 5.2.3 on 2025-07-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0022_alter_randevu_hizmet_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='durum',
            field=models.CharField(choices=[('bekleyen', 'Bekleyen'), ('onaylandi', 'Onaylandı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='bekleyen', max_length=10, verbose_name='Durum'),
        ),
    ]
