# Generated by Django 5.2.3 on 2025-07-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu_app', '0023_alter_randevu_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='genelayar',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
